- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      docker pull 143471984431.dkr.ecr.ap-south-1.amazonaws.com/dev-backend:latest
      docker stop backend || true
      docker rm backend || true
      docker run -d -p 8000:8000 --name backend --restart always \
        143471984431.dkr.ecr.ap-south-1.amazonaws.com/dev-backend:latest